### PR TITLE
Use @implementer and @adapter class decorators for Python3 compatibility

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by ale-rt** [comment]
Also a release would be nice: https://pypi.org/project/htmllaundry/  CC @pysailor

**Review by pysailor — APPROVED** [review]
LGTM

**Comment by ale-rt** [comment]
Can we have a release?

**Comment by pysailor** [comment]
https://pypi.org/project/htmllaundry/2.2/
I also added you all as Owners to Pypi

**Comment by ale-rt** [comment]
Thanks

**Pull request merged**
